stages:
  - build

variables:
  PROJECT_DIR: "nearest-neighbor"

build-binaries:
  image: dbogatov/docker-images:pbc-latest
  stage: build
  script:
    - ls -la
    - cd ./$PROJECT_DIR
    - ls -la
    - make clean copy-libs install-libs binaries
    - ./bin/accuracy
  needs:
    - project: bu/dcpe/scheme
      job: release-library
      ref: master
      artifacts: true
  tags:
    - docker
